### PR TITLE
Dev yearly average

### PR DESCRIPTION
**Pull request by NJJLarsson**

### CODE REVIEW

**Comment by NJJLarsson** [comment]
Cleaned up code and implemented in project.cpp

**Comment by AnttonLA** [comment]
Hej Jesper,
I've tried debugging your code before merging it but I'm running into other issues beyond the header file problem you mentioned (that seems fine actually). The file reading is giving me issues, even after including all the sanity checks I could think of. Have you tested that the files are parsed correctly for you?

I've included my modified version of your member function, can you check if it runs correclty whe you have the time?

/home/antton/MNXB01-project/code/src/tempTrender.cpp

Cheers,
Antton

**Comment by AnttonLA** [comment]
Hej Jesper,
I've tried debugging your code before merging it but I'm running into other issues beyond the header file problem you mentioned (that seems fine actually). The file reading is giving me issues, even after including all the sanity checks I could think of. Have you tested that the files are parsed correctly for you?

Here's my modified version of your member function. Could you check if it runs correctly for you when you have the time?

````
void tempTrender::tempMeanYearly(int yearStart, int yearEnd) const { //create a line-graph showin mean-yearly temperature over time.
  
//TODO: Modify code to separate date by "-" to check year, when the first year in our range is found, begin storing data
//Temp of each date must

  cout<<"The requested time period was " << yearStart << "-" << yearEnd << endl;

  //Create histogram to store our data
  //TH1D* hDayTemp = new TH1D("one_day_tempt", "Temperature for date;Temperature [C]; Entries", 100, -20, 40);
  
  //Code to open the csv files
  fstream fin; //File pointer
  fin.open(_path, ios::in); //Open file at '_path'
  if (fin.fail()) { //Check that file can be opened.
    cout << "File could not be opened. Please check that the provided path is correct." << endl;
	  return;
  };

  //Iterate through file, line by line, checking if the date matches with input
  vector<string> row, rowdate;
  string line, cell, date_string, Last_Date;

  double tempentry; 
  double tempdailysum = 0; 
  double tempyearlysum = 0;
  int sumentries = 0;
  vector<double> tempdailyaverage, YearlyAverage;
  double  tempyearlyaverage;
  int i = 0 ;
  int Year_Last = 0;
  int Year_Count = 0;
  int YearCurrent;

  while (getline(fin, line)){ //read whole file, row by row, store line in variable 'line' each loop
    i++;
    row.clear();
    rowdate.clear();
    cout << line << endl;
    stringstream lineStream(line); //Slice line by ; and store each part in vector 'row'
	while (lineStream.good() && getline(lineStream, cell, ';')) {
        row.push_back(cell);
    }
	date_string = row[0]; //save the date of the line
    cout << date_string << endl;
    if (any_of(date_string.begin(), date_string.end(), ::isdigit)) { //crude check to see if 'date_string' is indeed a date
      stringstream dateStream(date_string);
      while (dateStream.good() && getline(dateStream, date_string, '-')) { //slice date string by "-" and save to vector 'rowdata'
        rowdate.push_back(date_string);
      }
      YearCurrent = stoi(rowdate[0]);  // Save year to integer
      cout << YearCurrent << endl;
      //If the year is within the specified range
      if (YearCurrent>=yearStart && YearCurrent<= yearEnd) {
        //cout << "If accessed!" << endl;
        tempentry = stoi(row[2]) ;  //Check wheter current date matches last
        if (Last_Date.empty() || Last_Date==date_string){
        //If yes: add temp entry to the sum of the days entries, increase sum of the entries by one
          tempdailysum += tempentry ;
          sumentries++ ;
        }
      }
    }
}
````

Cheers,
Antton

**Comment by NJJLarsson** [comment]
Hi, I'll give it a look

**Comment by NJJLarsson** [comment]
This should work besides the part where it doesn't want to save the year string to an integer:


void tempTrender::tempMeanYearly(int yearStart, int yearEnd) const { //create a line-graph showin mean-yearly temperature over time.
  


  cout<<"The requested time period was " << yearStart << "-" << yearEnd << endl;

  //Create histogram to store our data
  //TH1D* hDayTemp = new TH1D("one_day_tempt", "Temperature for date;Temperature [C]; Entries", 100, -20, 40);
  
  //Code to open the csv files
  fstream fin; //File pointer
  fin.open(_path, ios::in); //Open file at '_path'
  if (fin.fail()) { //Check that file can be opened.
    cout << "File could not be opened. Please check that the provided path is correct." << endl;
	  return;
  };

    //Iterate through file, line by line, checking if the date matches with input
  vector<string> row, rowdate;
  
  string line, cell, date_string, YearString, Last_Date;

  double tempentry; 
  double tempdailysum = 0; 
  double tempyearlysum = 0;
  int sumentries = 0;
  vector<double> tempdailyaverage, YearlyAverage;
  double  tempyearlyaverage;
  int i = 0 ;
  int Year_Last = 0;
  int Year_Count = 0;
  int YearCurrent;

  while (getline(fin, line)){ //read whole file, row by row, store line in variable 'line' each loop
    i++;
    row.clear();

    stringstream lineStream(line); //Slice line by ; and store each part in vector 'row'
	while (lineStream.good() && getline(lineStream, cell, ';')) {
    row.push_back(cell);
  }
	date_string = row[0]; //save the date of the line 
  
  YearString = date_string.substr(0, 4);
  //cout << YearString << endl;
  //YearCurrent = stoi(YearString);  //TODO: Get this to save to an integer properly
    // Save year to integer
  //If the year is within the specified range
  if (YearCurrent>=yearStart && YearCurrent<= yearEnd) {
    tempentry = stoi(row[2]) ;  //Check wheter current date matches last
    if (Last_Date.empty() || Last_Date==date_string){ //If yes: add temp entry to the sum of the days entries, increase sum of the entries by one
      tempdailysum += tempentry ;
      sumentries++ ;

    } else{
      tempdailyaverage.push_back((tempdailysum / sumentries)); //if not: add sum to vector containing all daily averages, then zero tempdailysum & sumentries
      tempdailysum = 0;
      sumentries = 0;
      Year_Count++;
      //Then perform the same action as otherwise
      tempdailysum += tempentry ;
      sumentries++ ;
      if(Year_Last == 0 || Year_Last==YearCurrent){ //If year has changed, sum up all daily entries and average them out.
        tempyearlyaverage = VecAvg(tempdailyaverage);
        tempdailyaverage.clear();
        YearlyAverage.push_back(tempyearlyaverage);
      }
    }
      
      
  }
    //update a copy of the date to check against in the next iteration
    Last_Date = date_string;
    Year_Last = YearCurrent; //For testing cut
  }
  cout << "The average temperatures of " << YearlyAverage.size() << " years were calculated" << endl;
}

**Pull request merged**
